### ISSUE TITLE
Dominant Color Picker not visible in Backend (typo3 v 8.7.10)

### ISSUE THREAD

**Issue by ratron** [fsaris/lazy_load_placeholder#1]
after uploading and activating the extension (and clearing all caches - OPcache included) the dominant color field is not shown in the backend when you edit the files metadata

also: how can the DominantColorExtractor be executed?

**Comment by fsaris** [comment]
Do you have the cores EXT:filemetadata installed?

Extraction happens when the file gets uploaded/added when you have automatically extraction enabled for your storage (see storage settings, edit your file storage in the back end).
Or run the FAL scheduler task to extract metadata

**Comment by ratron** [comment]
thank you for yourt swift reply.

no, filemetadata was not activated. i added it as a dependency (see pull request) and now filemetadata installs automatically with your extension. i can see the dominant color field now.

however, it fails to extact the color because class 'ColorThief\ColorThief' cannot be found.
